# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ngquanghuy/Crypto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ngquanghuy/Crypto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ngquanghuy/Crypto/CMakeFiles /home/ngquanghuy/Crypto//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ngquanghuy/Crypto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crypto

# Build rule for target.
crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypto
.PHONY : crypto

# fast build rule for target.
crypto/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/build
.PHONY : crypto/fast

#=============================================================================
# Target rules for targets named test_crypto

# Build rule for target.
test_crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_crypto
.PHONY : test_crypto

# fast build rule for target.
test_crypto/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/build
.PHONY : test_crypto/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

src/cli/cli.o: src/cli/cli.cpp.o
.PHONY : src/cli/cli.o

# target to build an object file
src/cli/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/cli/cli.cpp.o
.PHONY : src/cli/cli.cpp.o

src/cli/cli.i: src/cli/cli.cpp.i
.PHONY : src/cli/cli.i

# target to preprocess a source file
src/cli/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/cli/cli.cpp.i
.PHONY : src/cli/cli.cpp.i

src/cli/cli.s: src/cli/cli.cpp.s
.PHONY : src/cli/cli.s

# target to generate assembly for a file
src/cli/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/cli/cli.cpp.s
.PHONY : src/cli/cli.cpp.s

src/cli/protect.o: src/cli/protect.cpp.o
.PHONY : src/cli/protect.o

# target to build an object file
src/cli/protect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/cli/protect.cpp.o
.PHONY : src/cli/protect.cpp.o

src/cli/protect.i: src/cli/protect.cpp.i
.PHONY : src/cli/protect.i

# target to preprocess a source file
src/cli/protect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/cli/protect.cpp.i
.PHONY : src/cli/protect.cpp.i

src/cli/protect.s: src/cli/protect.cpp.s
.PHONY : src/cli/protect.s

# target to generate assembly for a file
src/cli/protect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/cli/protect.cpp.s
.PHONY : src/cli/protect.cpp.s

src/crypto/aes.o: src/crypto/aes.cpp.o
.PHONY : src/crypto/aes.o

# target to build an object file
src/crypto/aes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/crypto/aes.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/crypto/aes.cpp.o
.PHONY : src/crypto/aes.cpp.o

src/crypto/aes.i: src/crypto/aes.cpp.i
.PHONY : src/crypto/aes.i

# target to preprocess a source file
src/crypto/aes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/crypto/aes.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/crypto/aes.cpp.i
.PHONY : src/crypto/aes.cpp.i

src/crypto/aes.s: src/crypto/aes.cpp.s
.PHONY : src/crypto/aes.s

# target to generate assembly for a file
src/crypto/aes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/crypto/aes.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/crypto/aes.cpp.s
.PHONY : src/crypto/aes.cpp.s

src/crypto/chacha20.o: src/crypto/chacha20.cpp.o
.PHONY : src/crypto/chacha20.o

# target to build an object file
src/crypto/chacha20.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/crypto/chacha20.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/crypto/chacha20.cpp.o
.PHONY : src/crypto/chacha20.cpp.o

src/crypto/chacha20.i: src/crypto/chacha20.cpp.i
.PHONY : src/crypto/chacha20.i

# target to preprocess a source file
src/crypto/chacha20.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/crypto/chacha20.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/crypto/chacha20.cpp.i
.PHONY : src/crypto/chacha20.cpp.i

src/crypto/chacha20.s: src/crypto/chacha20.cpp.s
.PHONY : src/crypto/chacha20.s

# target to generate assembly for a file
src/crypto/chacha20.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/crypto/chacha20.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/crypto/chacha20.cpp.s
.PHONY : src/crypto/chacha20.cpp.s

src/crypto/cipher.o: src/crypto/cipher.cpp.o
.PHONY : src/crypto/cipher.o

# target to build an object file
src/crypto/cipher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/crypto/cipher.cpp.o
.PHONY : src/crypto/cipher.cpp.o

src/crypto/cipher.i: src/crypto/cipher.cpp.i
.PHONY : src/crypto/cipher.i

# target to preprocess a source file
src/crypto/cipher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/crypto/cipher.cpp.i
.PHONY : src/crypto/cipher.cpp.i

src/crypto/cipher.s: src/crypto/cipher.cpp.s
.PHONY : src/crypto/cipher.s

# target to generate assembly for a file
src/crypto/cipher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/crypto/cipher.cpp.s
.PHONY : src/crypto/cipher.cpp.s

src/encode/ascii85.o: src/encode/ascii85.cpp.o
.PHONY : src/encode/ascii85.o

# target to build an object file
src/encode/ascii85.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/ascii85.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/ascii85.cpp.o
.PHONY : src/encode/ascii85.cpp.o

src/encode/ascii85.i: src/encode/ascii85.cpp.i
.PHONY : src/encode/ascii85.i

# target to preprocess a source file
src/encode/ascii85.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/ascii85.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/ascii85.cpp.i
.PHONY : src/encode/ascii85.cpp.i

src/encode/ascii85.s: src/encode/ascii85.cpp.s
.PHONY : src/encode/ascii85.s

# target to generate assembly for a file
src/encode/ascii85.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/ascii85.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/ascii85.cpp.s
.PHONY : src/encode/ascii85.cpp.s

src/encode/base32.o: src/encode/base32.cpp.o
.PHONY : src/encode/base32.o

# target to build an object file
src/encode/base32.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/base32.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/base32.cpp.o
.PHONY : src/encode/base32.cpp.o

src/encode/base32.i: src/encode/base32.cpp.i
.PHONY : src/encode/base32.i

# target to preprocess a source file
src/encode/base32.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/base32.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/base32.cpp.i
.PHONY : src/encode/base32.cpp.i

src/encode/base32.s: src/encode/base32.cpp.s
.PHONY : src/encode/base32.s

# target to generate assembly for a file
src/encode/base32.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/base32.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/base32.cpp.s
.PHONY : src/encode/base32.cpp.s

src/encode/base64.o: src/encode/base64.cpp.o
.PHONY : src/encode/base64.o

# target to build an object file
src/encode/base64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/base64.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/base64.cpp.o
.PHONY : src/encode/base64.cpp.o

src/encode/base64.i: src/encode/base64.cpp.i
.PHONY : src/encode/base64.i

# target to preprocess a source file
src/encode/base64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/base64.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/base64.cpp.i
.PHONY : src/encode/base64.cpp.i

src/encode/base64.s: src/encode/base64.cpp.s
.PHONY : src/encode/base64.s

# target to generate assembly for a file
src/encode/base64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/base64.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/base64.cpp.s
.PHONY : src/encode/base64.cpp.s

src/encode/base85.o: src/encode/base85.cpp.o
.PHONY : src/encode/base85.o

# target to build an object file
src/encode/base85.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/base85.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/base85.cpp.o
.PHONY : src/encode/base85.cpp.o

src/encode/base85.i: src/encode/base85.cpp.i
.PHONY : src/encode/base85.i

# target to preprocess a source file
src/encode/base85.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/base85.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/base85.cpp.i
.PHONY : src/encode/base85.cpp.i

src/encode/base85.s: src/encode/base85.cpp.s
.PHONY : src/encode/base85.s

# target to generate assembly for a file
src/encode/base85.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/base85.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/base85.cpp.s
.PHONY : src/encode/base85.cpp.s

src/encode/encoder.o: src/encode/encoder.cpp.o
.PHONY : src/encode/encoder.o

# target to build an object file
src/encode/encoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/encoder.cpp.o
.PHONY : src/encode/encoder.cpp.o

src/encode/encoder.i: src/encode/encoder.cpp.i
.PHONY : src/encode/encoder.i

# target to preprocess a source file
src/encode/encoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/encoder.cpp.i
.PHONY : src/encode/encoder.cpp.i

src/encode/encoder.s: src/encode/encoder.cpp.s
.PHONY : src/encode/encoder.s

# target to generate assembly for a file
src/encode/encoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/encoder.cpp.s
.PHONY : src/encode/encoder.cpp.s

src/encode/hexcode.o: src/encode/hexcode.cpp.o
.PHONY : src/encode/hexcode.o

# target to build an object file
src/encode/hexcode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/hexcode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/hexcode.cpp.o
.PHONY : src/encode/hexcode.cpp.o

src/encode/hexcode.i: src/encode/hexcode.cpp.i
.PHONY : src/encode/hexcode.i

# target to preprocess a source file
src/encode/hexcode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/hexcode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/hexcode.cpp.i
.PHONY : src/encode/hexcode.cpp.i

src/encode/hexcode.s: src/encode/hexcode.cpp.s
.PHONY : src/encode/hexcode.s

# target to generate assembly for a file
src/encode/hexcode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/hexcode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/hexcode.cpp.s
.PHONY : src/encode/hexcode.cpp.s

src/encode/xorcode.o: src/encode/xorcode.cpp.o
.PHONY : src/encode/xorcode.o

# target to build an object file
src/encode/xorcode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/xorcode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/xorcode.cpp.o
.PHONY : src/encode/xorcode.cpp.o

src/encode/xorcode.i: src/encode/xorcode.cpp.i
.PHONY : src/encode/xorcode.i

# target to preprocess a source file
src/encode/xorcode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/xorcode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/xorcode.cpp.i
.PHONY : src/encode/xorcode.cpp.i

src/encode/xorcode.s: src/encode/xorcode.cpp.s
.PHONY : src/encode/xorcode.s

# target to generate assembly for a file
src/encode/xorcode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/encode/xorcode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/encode/xorcode.cpp.s
.PHONY : src/encode/xorcode.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/obfuscate/anti_debug.o: src/obfuscate/anti_debug.cpp.o
.PHONY : src/obfuscate/anti_debug.o

# target to build an object file
src/obfuscate/anti_debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/anti_debug.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/anti_debug.cpp.o
.PHONY : src/obfuscate/anti_debug.cpp.o

src/obfuscate/anti_debug.i: src/obfuscate/anti_debug.cpp.i
.PHONY : src/obfuscate/anti_debug.i

# target to preprocess a source file
src/obfuscate/anti_debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/anti_debug.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/anti_debug.cpp.i
.PHONY : src/obfuscate/anti_debug.cpp.i

src/obfuscate/anti_debug.s: src/obfuscate/anti_debug.cpp.s
.PHONY : src/obfuscate/anti_debug.s

# target to generate assembly for a file
src/obfuscate/anti_debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/anti_debug.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/anti_debug.cpp.s
.PHONY : src/obfuscate/anti_debug.cpp.s

src/obfuscate/flow_flatten.o: src/obfuscate/flow_flatten.cpp.o
.PHONY : src/obfuscate/flow_flatten.o

# target to build an object file
src/obfuscate/flow_flatten.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/flow_flatten.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/flow_flatten.cpp.o
.PHONY : src/obfuscate/flow_flatten.cpp.o

src/obfuscate/flow_flatten.i: src/obfuscate/flow_flatten.cpp.i
.PHONY : src/obfuscate/flow_flatten.i

# target to preprocess a source file
src/obfuscate/flow_flatten.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/flow_flatten.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/flow_flatten.cpp.i
.PHONY : src/obfuscate/flow_flatten.cpp.i

src/obfuscate/flow_flatten.s: src/obfuscate/flow_flatten.cpp.s
.PHONY : src/obfuscate/flow_flatten.s

# target to generate assembly for a file
src/obfuscate/flow_flatten.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/flow_flatten.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/flow_flatten.cpp.s
.PHONY : src/obfuscate/flow_flatten.cpp.s

src/obfuscate/junk.o: src/obfuscate/junk.cpp.o
.PHONY : src/obfuscate/junk.o

# target to build an object file
src/obfuscate/junk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/junk.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/junk.cpp.o
.PHONY : src/obfuscate/junk.cpp.o

src/obfuscate/junk.i: src/obfuscate/junk.cpp.i
.PHONY : src/obfuscate/junk.i

# target to preprocess a source file
src/obfuscate/junk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/junk.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/junk.cpp.i
.PHONY : src/obfuscate/junk.cpp.i

src/obfuscate/junk.s: src/obfuscate/junk.cpp.s
.PHONY : src/obfuscate/junk.s

# target to generate assembly for a file
src/obfuscate/junk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/junk.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/junk.cpp.s
.PHONY : src/obfuscate/junk.cpp.s

src/obfuscate/obfuscate.o: src/obfuscate/obfuscate.cpp.o
.PHONY : src/obfuscate/obfuscate.o

# target to build an object file
src/obfuscate/obfuscate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/obfuscate.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/obfuscate.cpp.o
.PHONY : src/obfuscate/obfuscate.cpp.o

src/obfuscate/obfuscate.i: src/obfuscate/obfuscate.cpp.i
.PHONY : src/obfuscate/obfuscate.i

# target to preprocess a source file
src/obfuscate/obfuscate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/obfuscate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/obfuscate.cpp.i
.PHONY : src/obfuscate/obfuscate.cpp.i

src/obfuscate/obfuscate.s: src/obfuscate/obfuscate.cpp.s
.PHONY : src/obfuscate/obfuscate.s

# target to generate assembly for a file
src/obfuscate/obfuscate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/obfuscate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/obfuscate.cpp.s
.PHONY : src/obfuscate/obfuscate.cpp.s

src/obfuscate/rename.o: src/obfuscate/rename.cpp.o
.PHONY : src/obfuscate/rename.o

# target to build an object file
src/obfuscate/rename.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/rename.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/rename.cpp.o
.PHONY : src/obfuscate/rename.cpp.o

src/obfuscate/rename.i: src/obfuscate/rename.cpp.i
.PHONY : src/obfuscate/rename.i

# target to preprocess a source file
src/obfuscate/rename.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/rename.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/rename.cpp.i
.PHONY : src/obfuscate/rename.cpp.i

src/obfuscate/rename.s: src/obfuscate/rename.cpp.s
.PHONY : src/obfuscate/rename.s

# target to generate assembly for a file
src/obfuscate/rename.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/rename.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/rename.cpp.s
.PHONY : src/obfuscate/rename.cpp.s

src/obfuscate/xor_gen.o: src/obfuscate/xor_gen.cpp.o
.PHONY : src/obfuscate/xor_gen.o

# target to build an object file
src/obfuscate/xor_gen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/xor_gen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/xor_gen.cpp.o
.PHONY : src/obfuscate/xor_gen.cpp.o

src/obfuscate/xor_gen.i: src/obfuscate/xor_gen.cpp.i
.PHONY : src/obfuscate/xor_gen.i

# target to preprocess a source file
src/obfuscate/xor_gen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/xor_gen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/xor_gen.cpp.i
.PHONY : src/obfuscate/xor_gen.cpp.i

src/obfuscate/xor_gen.s: src/obfuscate/xor_gen.cpp.s
.PHONY : src/obfuscate/xor_gen.s

# target to generate assembly for a file
src/obfuscate/xor_gen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/obfuscate/xor_gen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/obfuscate/xor_gen.cpp.s
.PHONY : src/obfuscate/xor_gen.cpp.s

src/utils/compress.o: src/utils/compress.cpp.o
.PHONY : src/utils/compress.o

# target to build an object file
src/utils/compress.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/utils/compress.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/utils/compress.cpp.o
.PHONY : src/utils/compress.cpp.o

src/utils/compress.i: src/utils/compress.cpp.i
.PHONY : src/utils/compress.i

# target to preprocess a source file
src/utils/compress.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/utils/compress.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/utils/compress.cpp.i
.PHONY : src/utils/compress.cpp.i

src/utils/compress.s: src/utils/compress.cpp.s
.PHONY : src/utils/compress.s

# target to generate assembly for a file
src/utils/compress.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/utils/compress.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/utils/compress.cpp.s
.PHONY : src/utils/compress.cpp.s

src/utils/file_util.o: src/utils/file_util.cpp.o
.PHONY : src/utils/file_util.o

# target to build an object file
src/utils/file_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/utils/file_util.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/utils/file_util.cpp.o
.PHONY : src/utils/file_util.cpp.o

src/utils/file_util.i: src/utils/file_util.cpp.i
.PHONY : src/utils/file_util.i

# target to preprocess a source file
src/utils/file_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/utils/file_util.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/utils/file_util.cpp.i
.PHONY : src/utils/file_util.cpp.i

src/utils/file_util.s: src/utils/file_util.cpp.s
.PHONY : src/utils/file_util.s

# target to generate assembly for a file
src/utils/file_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/utils/file_util.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/utils/file_util.cpp.s
.PHONY : src/utils/file_util.cpp.s

src/vm/cfi.o: src/vm/cfi.cpp.o
.PHONY : src/vm/cfi.o

# target to build an object file
src/vm/cfi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/cfi.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/cfi.cpp.o
.PHONY : src/vm/cfi.cpp.o

src/vm/cfi.i: src/vm/cfi.cpp.i
.PHONY : src/vm/cfi.i

# target to preprocess a source file
src/vm/cfi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/cfi.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/cfi.cpp.i
.PHONY : src/vm/cfi.cpp.i

src/vm/cfi.s: src/vm/cfi.cpp.s
.PHONY : src/vm/cfi.s

# target to generate assembly for a file
src/vm/cfi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/cfi.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/cfi.cpp.s
.PHONY : src/vm/cfi.cpp.s

src/vm/code_schedule.o: src/vm/code_schedule.cpp.o
.PHONY : src/vm/code_schedule.o

# target to build an object file
src/vm/code_schedule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/code_schedule.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/code_schedule.cpp.o
.PHONY : src/vm/code_schedule.cpp.o

src/vm/code_schedule.i: src/vm/code_schedule.cpp.i
.PHONY : src/vm/code_schedule.i

# target to preprocess a source file
src/vm/code_schedule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/code_schedule.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/code_schedule.cpp.i
.PHONY : src/vm/code_schedule.cpp.i

src/vm/code_schedule.s: src/vm/code_schedule.cpp.s
.PHONY : src/vm/code_schedule.s

# target to generate assembly for a file
src/vm/code_schedule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/code_schedule.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/code_schedule.cpp.s
.PHONY : src/vm/code_schedule.cpp.s

src/vm/isa_expand.o: src/vm/isa_expand.cpp.o
.PHONY : src/vm/isa_expand.o

# target to build an object file
src/vm/isa_expand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/isa_expand.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/isa_expand.cpp.o
.PHONY : src/vm/isa_expand.cpp.o

src/vm/isa_expand.i: src/vm/isa_expand.cpp.i
.PHONY : src/vm/isa_expand.i

# target to preprocess a source file
src/vm/isa_expand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/isa_expand.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/isa_expand.cpp.i
.PHONY : src/vm/isa_expand.cpp.i

src/vm/isa_expand.s: src/vm/isa_expand.cpp.s
.PHONY : src/vm/isa_expand.s

# target to generate assembly for a file
src/vm/isa_expand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/isa_expand.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/isa_expand.cpp.s
.PHONY : src/vm/isa_expand.cpp.s

src/vm/obfcond.o: src/vm/obfcond.cpp.o
.PHONY : src/vm/obfcond.o

# target to build an object file
src/vm/obfcond.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/obfcond.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/obfcond.cpp.o
.PHONY : src/vm/obfcond.cpp.o

src/vm/obfcond.i: src/vm/obfcond.cpp.i
.PHONY : src/vm/obfcond.i

# target to preprocess a source file
src/vm/obfcond.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/obfcond.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/obfcond.cpp.i
.PHONY : src/vm/obfcond.cpp.i

src/vm/obfcond.s: src/vm/obfcond.cpp.s
.PHONY : src/vm/obfcond.s

# target to generate assembly for a file
src/vm/obfcond.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/obfcond.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/obfcond.cpp.s
.PHONY : src/vm/obfcond.cpp.s

src/vm/smc.o: src/vm/smc.cpp.o
.PHONY : src/vm/smc.o

# target to build an object file
src/vm/smc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/smc.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/smc.cpp.o
.PHONY : src/vm/smc.cpp.o

src/vm/smc.i: src/vm/smc.cpp.i
.PHONY : src/vm/smc.i

# target to preprocess a source file
src/vm/smc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/smc.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/smc.cpp.i
.PHONY : src/vm/smc.cpp.i

src/vm/smc.s: src/vm/smc.cpp.s
.PHONY : src/vm/smc.s

# target to generate assembly for a file
src/vm/smc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/smc.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/smc.cpp.s
.PHONY : src/vm/smc.cpp.s

src/vm/spill.o: src/vm/spill.cpp.o
.PHONY : src/vm/spill.o

# target to build an object file
src/vm/spill.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/spill.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/spill.cpp.o
.PHONY : src/vm/spill.cpp.o

src/vm/spill.i: src/vm/spill.cpp.i
.PHONY : src/vm/spill.i

# target to preprocess a source file
src/vm/spill.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/spill.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/spill.cpp.i
.PHONY : src/vm/spill.cpp.i

src/vm/spill.s: src/vm/spill.cpp.s
.PHONY : src/vm/spill.s

# target to generate assembly for a file
src/vm/spill.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/spill.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/spill.cpp.s
.PHONY : src/vm/spill.cpp.s

src/vm/vlencode.o: src/vm/vlencode.cpp.o
.PHONY : src/vm/vlencode.o

# target to build an object file
src/vm/vlencode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/vlencode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/vlencode.cpp.o
.PHONY : src/vm/vlencode.cpp.o

src/vm/vlencode.i: src/vm/vlencode.cpp.i
.PHONY : src/vm/vlencode.i

# target to preprocess a source file
src/vm/vlencode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/vlencode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/vlencode.cpp.i
.PHONY : src/vm/vlencode.cpp.i

src/vm/vlencode.s: src/vm/vlencode.cpp.s
.PHONY : src/vm/vlencode.s

# target to generate assembly for a file
src/vm/vlencode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/vlencode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/vlencode.cpp.s
.PHONY : src/vm/vlencode.cpp.s

src/vm/vm_compile.o: src/vm/vm_compile.cpp.o
.PHONY : src/vm/vm_compile.o

# target to build an object file
src/vm/vm_compile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/vm_compile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/vm_compile.cpp.o
.PHONY : src/vm/vm_compile.cpp.o

src/vm/vm_compile.i: src/vm/vm_compile.cpp.i
.PHONY : src/vm/vm_compile.i

# target to preprocess a source file
src/vm/vm_compile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/vm_compile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/vm_compile.cpp.i
.PHONY : src/vm/vm_compile.cpp.i

src/vm/vm_compile.s: src/vm/vm_compile.cpp.s
.PHONY : src/vm/vm_compile.s

# target to generate assembly for a file
src/vm/vm_compile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/vm_compile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/vm_compile.cpp.s
.PHONY : src/vm/vm_compile.cpp.s

src/vm/vm_stub.o: src/vm/vm_stub.cpp.o
.PHONY : src/vm/vm_stub.o

# target to build an object file
src/vm/vm_stub.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/vm_stub.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/vm_stub.cpp.o
.PHONY : src/vm/vm_stub.cpp.o

src/vm/vm_stub.i: src/vm/vm_stub.cpp.i
.PHONY : src/vm/vm_stub.i

# target to preprocess a source file
src/vm/vm_stub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/vm_stub.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/vm_stub.cpp.i
.PHONY : src/vm/vm_stub.cpp.i

src/vm/vm_stub.s: src/vm/vm_stub.cpp.s
.PHONY : src/vm/vm_stub.s

# target to generate assembly for a file
src/vm/vm_stub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/vm/vm_stub.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/src/vm/vm_stub.cpp.s
.PHONY : src/vm/vm_stub.cpp.s

tests/test_all.o: tests/test_all.cpp.o
.PHONY : tests/test_all.o

# target to build an object file
tests/test_all.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/test_all.cpp.o
.PHONY : tests/test_all.cpp.o

tests/test_all.i: tests/test_all.cpp.i
.PHONY : tests/test_all.i

# target to preprocess a source file
tests/test_all.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/test_all.cpp.i
.PHONY : tests/test_all.cpp.i

tests/test_all.s: tests/test_all.cpp.s
.PHONY : tests/test_all.s

# target to generate assembly for a file
tests/test_all.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/test_all.cpp.s
.PHONY : tests/test_all.cpp.s

tests/test_obfuscate.o: tests/test_obfuscate.cpp.o
.PHONY : tests/test_obfuscate.o

# target to build an object file
tests/test_obfuscate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/test_obfuscate.cpp.o
.PHONY : tests/test_obfuscate.cpp.o

tests/test_obfuscate.i: tests/test_obfuscate.cpp.i
.PHONY : tests/test_obfuscate.i

# target to preprocess a source file
tests/test_obfuscate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/test_obfuscate.cpp.i
.PHONY : tests/test_obfuscate.cpp.i

tests/test_obfuscate.s: tests/test_obfuscate.cpp.s
.PHONY : tests/test_obfuscate.s

# target to generate assembly for a file
tests/test_obfuscate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/test_obfuscate.cpp.s
.PHONY : tests/test_obfuscate.cpp.s

tests/test_vm.o: tests/test_vm.cpp.o
.PHONY : tests/test_vm.o

# target to build an object file
tests/test_vm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/test_vm.cpp.o
.PHONY : tests/test_vm.cpp.o

tests/test_vm.i: tests/test_vm.cpp.i
.PHONY : tests/test_vm.i

# target to preprocess a source file
tests/test_vm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/test_vm.cpp.i
.PHONY : tests/test_vm.cpp.i

tests/test_vm.s: tests/test_vm.cpp.s
.PHONY : tests/test_vm.s

# target to generate assembly for a file
tests/test_vm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/test_vm.cpp.s
.PHONY : tests/test_vm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... crypto"
	@echo "... test_crypto"
	@echo "... src/cli/cli.o"
	@echo "... src/cli/cli.i"
	@echo "... src/cli/cli.s"
	@echo "... src/cli/protect.o"
	@echo "... src/cli/protect.i"
	@echo "... src/cli/protect.s"
	@echo "... src/crypto/aes.o"
	@echo "... src/crypto/aes.i"
	@echo "... src/crypto/aes.s"
	@echo "... src/crypto/chacha20.o"
	@echo "... src/crypto/chacha20.i"
	@echo "... src/crypto/chacha20.s"
	@echo "... src/crypto/cipher.o"
	@echo "... src/crypto/cipher.i"
	@echo "... src/crypto/cipher.s"
	@echo "... src/encode/ascii85.o"
	@echo "... src/encode/ascii85.i"
	@echo "... src/encode/ascii85.s"
	@echo "... src/encode/base32.o"
	@echo "... src/encode/base32.i"
	@echo "... src/encode/base32.s"
	@echo "... src/encode/base64.o"
	@echo "... src/encode/base64.i"
	@echo "... src/encode/base64.s"
	@echo "... src/encode/base85.o"
	@echo "... src/encode/base85.i"
	@echo "... src/encode/base85.s"
	@echo "... src/encode/encoder.o"
	@echo "... src/encode/encoder.i"
	@echo "... src/encode/encoder.s"
	@echo "... src/encode/hexcode.o"
	@echo "... src/encode/hexcode.i"
	@echo "... src/encode/hexcode.s"
	@echo "... src/encode/xorcode.o"
	@echo "... src/encode/xorcode.i"
	@echo "... src/encode/xorcode.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/obfuscate/anti_debug.o"
	@echo "... src/obfuscate/anti_debug.i"
	@echo "... src/obfuscate/anti_debug.s"
	@echo "... src/obfuscate/flow_flatten.o"
	@echo "... src/obfuscate/flow_flatten.i"
	@echo "... src/obfuscate/flow_flatten.s"
	@echo "... src/obfuscate/junk.o"
	@echo "... src/obfuscate/junk.i"
	@echo "... src/obfuscate/junk.s"
	@echo "... src/obfuscate/obfuscate.o"
	@echo "... src/obfuscate/obfuscate.i"
	@echo "... src/obfuscate/obfuscate.s"
	@echo "... src/obfuscate/rename.o"
	@echo "... src/obfuscate/rename.i"
	@echo "... src/obfuscate/rename.s"
	@echo "... src/obfuscate/xor_gen.o"
	@echo "... src/obfuscate/xor_gen.i"
	@echo "... src/obfuscate/xor_gen.s"
	@echo "... src/utils/compress.o"
	@echo "... src/utils/compress.i"
	@echo "... src/utils/compress.s"
	@echo "... src/utils/file_util.o"
	@echo "... src/utils/file_util.i"
	@echo "... src/utils/file_util.s"
	@echo "... src/vm/cfi.o"
	@echo "... src/vm/cfi.i"
	@echo "... src/vm/cfi.s"
	@echo "... src/vm/code_schedule.o"
	@echo "... src/vm/code_schedule.i"
	@echo "... src/vm/code_schedule.s"
	@echo "... src/vm/isa_expand.o"
	@echo "... src/vm/isa_expand.i"
	@echo "... src/vm/isa_expand.s"
	@echo "... src/vm/obfcond.o"
	@echo "... src/vm/obfcond.i"
	@echo "... src/vm/obfcond.s"
	@echo "... src/vm/smc.o"
	@echo "... src/vm/smc.i"
	@echo "... src/vm/smc.s"
	@echo "... src/vm/spill.o"
	@echo "... src/vm/spill.i"
	@echo "... src/vm/spill.s"
	@echo "... src/vm/vlencode.o"
	@echo "... src/vm/vlencode.i"
	@echo "... src/vm/vlencode.s"
	@echo "... src/vm/vm_compile.o"
	@echo "... src/vm/vm_compile.i"
	@echo "... src/vm/vm_compile.s"
	@echo "... src/vm/vm_stub.o"
	@echo "... src/vm/vm_stub.i"
	@echo "... src/vm/vm_stub.s"
	@echo "... tests/test_all.o"
	@echo "... tests/test_all.i"
	@echo "... tests/test_all.s"
	@echo "... tests/test_obfuscate.o"
	@echo "... tests/test_obfuscate.i"
	@echo "... tests/test_obfuscate.s"
	@echo "... tests/test_vm.o"
	@echo "... tests/test_vm.i"
	@echo "... tests/test_vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

