#!/usr/bin/env python3
"""
Generate include/vm/vm_interp_py.h from include/vm/vm_runtime_source.py.

This generator:
1. Reads the VM runtime source (single source of truth)
2. Optionally pipes through pyobf.py with rename,cleanup (safe passes only)
3. Generates marshalled bytecode bytes for the stub bootstrap
4. Emits include/vm/vm_interp_py.h containing both:
   - VM_INTERP_SCRIPT: obfuscated source (fallback/debugging)
   - VM_INTERP_MARSHAL: base64-encoded marshalled bytecode (primary path)

Usage: python3 tools/generate_vm_interp_h.py [--no-obfuscate]
"""
import os
import sys
import subprocess
import base64
import marshal
import hashlib

_TOOLS_DIR = os.path.dirname(__file__ or '.')
_PROJECT_DIR = os.path.normpath(os.path.join(_TOOLS_DIR, '..'))
_SOURCE_PATH = os.path.join(_PROJECT_DIR, 'include/vm/vm_runtime_source.py')
_HEADER_PATH = os.path.join(_PROJECT_DIR, 'include/vm/vm_interp_py.h')
_PYOBF_PATH = os.path.join(_TOOLS_DIR, 'pyobf.py')


def run_pyobf(source, seed=None):
    """Pipe source through pyobf.py rename,cleanup."""
    cmd = [sys.executable, _PYOBF_PATH, "rename,cleanup"]
    if seed is not None:
        cmd.append("--seed")
        cmd.append(str(seed))

    try:
        result = subprocess.run(
            cmd,
            input=source,
            capture_output=True,
            text=True,
            timeout=30
        )
        if result.returncode == 0 and result.stdout:
            return result.stdout
        # Fallback on error - pyobf may have syntax issues
        print(f"WARNING: pyobf failed, using original source", file=sys.stderr)
        print(f"  stderr: {result.stderr[:200]}", file=sys.stderr)
        return source
    except Exception as e:
        print(f"WARNING: pyobf exception: {e}, using original source", file=sys.stderr)
        return source


def obfuscate_source(source, seed=None):
    """Try to obfuscate source with pyobf rename,cleanup passes."""
    # Check syntax first
    try:
        compile(source, '<vm_runtime>', 'exec')
    except SyntaxError as e:
        print(f"ERROR: Source has syntax error: {e}", file=sys.stderr)
        return source, False

    try:
        obf = run_pyobf(source, seed)
        compile(obf, '<vm_runtime>', 'exec')
        return obf, True
    except SyntaxError as e:
        print(f"WARNING: Obfuscation broke syntax: {e}", file=sys.stderr)
        return source, False


def generate_header(obfuscate=True, seed=42):
    """Generate vm_interp_py.h header file."""
    with open(_SOURCE_PATH, 'r') as f:
        source = f.read()

    source_md5 = hashlib.md5(source.encode()).hexdigest()

    if obfuscate:
        print(f"Obfuscating VM runtime with seed={seed}...")
        obf_source, success = obfuscate_source(source, seed)
        obfuscated_md5 = hashlib.md5(obf_source.encode()).hexdigest()
        if success:
            print(f"  Obfuscation successful (md5: {obfuscated_md5[:8]}...)")
        else:
            print(f"  Obfuscation failed, using original source")
            obf_source = source
    else:
        obf_source = source
        obfuscated_md5 = source_md5

    # Compile and marshal
    code = compile(obf_source, '<vm_runtime>', 'exec')
    marshal_bytes = marshal.dumps(code)
    marshal_b64 = base64.b64encode(marshal_bytes).decode('ascii')
    marshal_size = len(marshal_bytes)

    print(f"Marshal size: {marshal_size} bytes ({marshal_size // 1024}KB)")
    print(f"Base64 size: {len(marshal_b64)} characters")

    # Generate header
    header = f'''\
#ifndef CRYPTO_VM_INTERP_PY_H
#define CRYPTO_VM_INTERP_PY_H

/*
 * THIS FILE IS AUTO-GENERATED from include/vm/vm_runtime_source.py
 * by tools/generate_vm_interp_h.py.  Do NOT edit directly.
 *
 * Source MD5: {source_md5}
 * Obfuscated MD5: {obfuscated_md5}
 * Marshal size: {marshal_size} bytes
 * Generated by: python3 {" ".join(sys.argv)}
 *
 * To regenerate:
 *     python3 tools/generate_vm_interp_h.py
 *
 * VM runtime is embedded in two forms:
 *   VM_INTERP_SCRIPT  - Python source (fallback/debugging only)
 *   VM_INTERP_MARSHAL - Base64-encoded marshalled bytecode (primary)
 */

'''

    # Add VM_INTERP_SCRIPT (obfuscated source as raw string)
    # In C++ raw string R"delim(...)delim", quotes are literal (no escape needed)
    # BUT backslash IS literal too in raw strings, so NO escaping needed for the content!
    # The ONLY restriction is that the delimiter sequence )X" cannot appear inside.
    # Use a long unique delimiter that won't appear in Python source.
    delim = "_XaBcD98fGhIjK"
    _start = 'static const char VM_INTERP_SCRIPT[] = '
    _open = f'R"{delim}('
    _close = f'\n){delim}";' + '\n\n'
    header += _start + _open
    header += obf_source
    header += _close

    # Add VM_INTERP_MARSHAL (base64-encoded marshal bytes)
    # Output as single line to avoid Python triple-quote multi-line issues
    header += f'// Base64-encoded marshalled Python bytecode ({marshal_size} bytes)\n'
    header += '// Bootstrapped with: exec(marshal.loads(base64.b64decode(VM_INTERP_MARSHAL)))\n'
    header += 'static const char VM_INTERP_MARSHAL[] = "' + marshal_b64 + '";\n'

    header += f'''
// Size of marshalled bytecode (for validation)
static const size_t VM_INTERP_MARSHAL_SIZE = {marshal_size};

// CRC32 of marshal bytes (for basic integrity check)
static const unsigned int VM_INTERP_MARSHAL_CRC = 0x{marshal_crc32(marshal_bytes):08x};

#endif /* CRYPTO_VM_INTERP_PY_H */
'''

    with open(_HEADER_PATH, 'w') as f:
        f.write(header)

    print(f"Generated {_HEADER_PATH}")


def marshal_crc32(data):
    """Calculate CRC32 of bytes."""
    import zlib
    return zlib.crc32(data) & 0xffffffff


def main():
    obfuscate = "--no-obfuscate" not in sys.argv

    # Check Python version for compatibility note
    print(f"Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")

    generate_header(obfuscate=obfuscate, seed=42)


if __name__ == '__main__':
    main()